name: Deployment
on:
  push:
    branches:
      - main

jobs:
  App-Build:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
      - name: Use Node.js for build test
        uses: actions/setup-node@v3
      - run: npm ci
      - run: npm run build

  Docker-Build-and-Push-DockerRegistry:
    needs: App-Build
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
      - name: Docker Build
        run: docker build -t oshan9/react-app:latest .
      - name: Docker Images to check the image
        run: docker images
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          logout: true
      - name: Push to registry
        run: docker push oshan9/react-app:latest
